services:
  api:
    container_name: address-complete-divide-api
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./data:/app/data
      - ~/.aws/:/root/.aws:ro
    ports:
      - 8000:8000
    tty: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
