# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "sam-app"

[default.build]
[default.build.parameters]
cached = false
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
s3_prefix = "address-complete-divide-api"
region = "ap-northeast-1"
disable_rollback = true
image_repositories = []
stack_name = "address-complete-divide-api"
resolve_s3 = true

[default.package]
[default.package.parameters]
[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
