name: Pytest
on: push
permissions: write-all

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest --cov --junitxml=pytest.xml --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Create Coverage Comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
            pytest-coverage-path: pytest-coverage.txt
            junitxml-path: ./pytest.xml

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.3.0
        with:
            auth: ${{ secrets.BADGE_GIST }}
            gistID: 9c19de175b7ce5bcfd2eb2ed26a60d40

            filename: raw/pytest-coverage-comment.json
            label: Coverage
            message: ${{ steps.coverageComment.outputs.coverage }}
            color: ${{ steps.coverageComment.outputs.color }}
            namedLogo: python